In [4]:
import numpy as np

arr1 = np.array([[1,2,3], [4,5,6]])  # (2,3)
arr2 = np.array([[4,5],[6,7],[8,9]]) # (3,2)
print(np.matmul(arr1, arr2))         # 행렬곱연산. matmul() 함수 사용해서 계산. 결과는 (2,2)
# [[ 40  46]
#  [ 94 109]]

[[ 40  46]
 [ 94 109]]


In [5]:
# 전치행렬(transpose). 행은 열로, 열은 행으로 바꿔줌
arr = np.array([[1,2,3], [4,5,6]])   #(2,3)
print(arr)
print(arr.T) # T라는 속성을 사용. (3,2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [20]:
# iterator(반복자)를 이용한 반복문 처리. ndarray는 python의 for문과 달리 while문과 iterator를 이용
arr = np.array([1,2,3,4,5]) # (5,)

# for tmp in arr: # python의 for문
#     print(tmp)

my_iter = np.nditer(arr, flags=['c_index']) # iterator 객체를 얻어옮. 변수 넣고 flags라는 속성으로 차원 정해줌. 1차원
# print(my_iter)           # <numpy.nditer object at 0x0000019C75B253F0> 인덱스 값 출력

while not my_iter.finished: # my_iter의 iterator가 가르치는 값이 끝이 아니면 계속 반복(True)
    idx = my_iter.index
    print(arr[idx])         # index의 요소 출력
    my_iter.iternext()      # iterator 다음으로 이동
# 1
# 2
# 3
# 4
# 5

1
2
3
4
5


In [34]:
arr = np.array([[1,2,3],[4,5,6]])                # (2,3)

# for tmp1 in range(arr.shape[0]):               # 행에 대한 range. range(2). 2차원이니까 for문 2번
#     for tmp2 in range(arr.shape[1]):           # 열에 대한 range. range(3)
#         print(arr[tmp1, tmp2])

my_iter = np.nditer(arr, flags=['multi_index']) # flags 속성은 다차원
while not my_iter.finished:
    idx = my_iter.multi_index                   # 다차원에서는 multi_index 메서드 사용
#     print(idx)
    print(arr[idx], idx)
    my_iter.iternext()
# 1 (0, 0)
# 2 (0, 1)
# 3 (0, 2)
# 4 (1, 0)
# 5 (1, 1)
# 6 (1, 2)

1 (0, 0)
2 (0, 1)
3 (0, 2)
4 (1, 0)
5 (1, 1)
6 (1, 2)


In [41]:
# 집계함수
arr = np.arange(1,7,1).reshape(2,3) # reshape로 원본 ndarray의 view를 2행 3열로 만듦
print(arr)          # [[1 2 3]
                    # [4 5 6]]
    
print(np.sum(arr))  # 21. 모든 요소의 합. Numpy가 제공하는 함수
print(arr.sum())    # 21. ndarray가 가진 메서드
print(arr.mean())   # 3.5. 평균
print(arr.max())    # 6. 최대값
print(arr.min())    # 1. 최소값
print(arr.argmax()) # 5. 가장 큰 값의 인덱스
print(arr.std())    # 1.707825127659933. 표준편차

[[1 2 3]
 [4 5 6]]
21
21
3.5
6
1
5
1.707825127659933


In [44]:
# axis(축) 개념. 0부터 시작하는 축을 숫자로 표현. ndarray는 축을 지정해주지 않으면 전체에 대해 연산함. 다차원에서는 axis가 바뀜

arr = np.arange(1,7,1).reshape(2,3)
print(arr)             # [[1 2 3]
                       # [4 5 6]]
print(arr.sum(axis=0)) # [5 7 9]. 행 방향 axis를 부여해서 열끼리 합을 구함
print(arr.sum(axis=1)) # [ 6 15]. 열 방향 axis를 부여해서 행끼리 합을 구함

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [65]:
# 연습문제. 이 안에 10보다 큰 수는 몇 개? 6개! cf) Boolean indexing
arr = np.arange(1, 17, 1).reshape(4,4)
print(arr)

my_mask = (arr > 10)
# print(arr[my_mask])
print(len(arr[my_mask]))
print(my_mask.sum())

print((arr > 10))       # Boolean indexing
print((arr > 10).sum()) # True = 1. True를 모두 더해라!

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
6
6
[[False False False False]
 [False False False False]
 [False False  True  True]
 [ True  True  True  True]]
6
